

import pyautogui 
import time


rep = 8

# Simula um clique do mouse na posição especificada
pyautogui.click(x=570, y=1050)
    
    # Aguarda um breve intervalo antes de simular o atalho Ctrl+V
time

for i in range(rep):

    pyautogui.hotkey('ctrl', 'c')
    time.sleep(2)

    pyautogui.click(x=510, y=1050)
    time.sleep(2)



    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')
    pyautogui.hotkey('backspace')

    pyautogui.hotkey('ctrl', 'v')
    time.sleep(5)

    pyautogui.click(x=36, y=77)
    time.sleep(2)
    pyautogui.click(x=99, y=531)
    time.sleep(2)
    pyautogui.click(x=780, y=181)
    time.sleep(2)


    pyautogui.hotkey('backspace')

    pyautogui.hotkey('A')
    pyautogui.hotkey('1')
    pyautogui.hotkey('5')
    pyautogui.hotkey('space') 
    pyautogui.hotkey('space') 
    pyautogui.hotkey('space') 

    pyautogui.hotkey('ctrl', 'v')
    

    pyautogui.click(x=1540, y=247)

    time.sleep(5)

    pyautogui.click(x=36, y=77)

    pyautogui.click(x=90, y=577)

    pyautogui.click(x=280, y=180)

    time.sleep(5)

    pyautogui.click(x=570, y=1050)

    pyautogui.hotkey('down') 
